#!/bin/bash

verbose=0
files=()
for arg in "$@"; do
    if [[ ! "$arg" == -* ]]; then
        files+=("$arg")
    elif [[ "$arg" == -v ]]; then
        verbose=1
    fi
done

if [[ ${#files[@]} == 0 ]]; then
    (>&2 echo "No files specified")
fi
for arg in "${files[@]}"; do
    if [[ -f "$arg" ]]; then
        fullpath="$(cd $(dirname "$arg") && pwd -P)/$(basename "$arg")"
        [[ $verbose == "1" ]] && echo "Removing file: $fullpath"
        osascript -e 'tell app "Finder" to move the POSIX file "'"$fullpath"'" to trash'
    else
        $(>&2 echo "File does not exists: ""$arg")
    fi
done
