#!/usr/bin/perl

open(CMDOUT, "-|", "/usr/bin/vm_stat", @ARGV) or die "Cannot open vm_stat";

while(<CMDOUT>) {
  if (/Mach Virtual Memory Statistics/) {
    print "Mach Virtual Memory Statistics: (Unit KB)\n";
  }
  else {
    print s/([0-9]+)/$1*4/ree;
  }
}
